"""add vault_sync_config table

Revision ID: 1b639e84d474
Revises: c2c533f5e0cb
Create Date: 2026-06-17 00:26:23.564358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b639e84d474'
down_revision = 'c2c533f5e0cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_sync_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kdbx_path', sa.String(length=500), nullable=False),
    sa.Column('kdbx_password_enc', sa.Text(), nullable=True),
    sa.Column('kdbx_keyfile_path', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_entry', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_entry', schema=None) as batch_op:
        batch_op.alter_column('uuid',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)

    op.drop_table('vault_sync_config')
    # ### end Alembic commands ###
