"""add knowledge attachment table

Revision ID: 36c6bc7ea6fa
Revises: 38fd8516d488
Create Date: 2026-10-08 17:00:46.196329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c6bc7ea6fa'
down_revision = '38fd8516d488'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('draft_token', sa.String(length=36), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('is_image', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('scan_status', sa.String(length=20), nullable=False),
    sa.Column('scan_checked_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('(article_id IS NOT NULL AND draft_token IS NULL) OR (article_id IS NULL AND draft_token IS NOT NULL)', name='ck_knowledge_attachment_exactly_one_owner'),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('knowledge_attachment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_attachment_article_id'), ['article_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_attachment_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_attachment_draft_token'), ['draft_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_attachment_scan_status'), ['scan_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_attachment_sha256'), ['sha256'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('knowledge_attachment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_attachment_sha256'))
        batch_op.drop_index(batch_op.f('ix_knowledge_attachment_scan_status'))
        batch_op.drop_index(batch_op.f('ix_knowledge_attachment_draft_token'))
        batch_op.drop_index(batch_op.f('ix_knowledge_attachment_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_attachment_article_id'))

    op.drop_table('knowledge_attachment')
    # ### end Alembic commands ###
