"""add knowledge base tables

Revision ID: 38fd8516d488
Revises: 1b639e84d474
Create Date: 2026-10-07 21:07:57.737147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fd8516d488'
down_revision = '1b639e84d474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_tag_name'), ['name'], unique=True)

    op.create_table('knowledge_article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('problem_md', sa.Text(), nullable=False),
    sa.Column('solution_md', sa.Text(), nullable=False),
    sa.Column('client', sa.String(length=120), nullable=True),
    sa.Column('platform', sa.String(length=120), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_article', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_article_client'), ['client'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_article_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_article_title'), ['title'], unique=False)

    op.create_table('knowledge_article_tag',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['knowledge_article.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['knowledge_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge_article_tag')
    with op.batch_alter_table('knowledge_article', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_article_title'))
        batch_op.drop_index(batch_op.f('ix_knowledge_article_platform'))
        batch_op.drop_index(batch_op.f('ix_knowledge_article_client'))

    op.drop_table('knowledge_article')
    with op.batch_alter_table('knowledge_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_tag_name'))

    op.drop_table('knowledge_tag')
    # ### end Alembic commands ###
