"""Remove checklist and credentials modules

Revision ID: 3cf82448f25f
Revises: 4da5b9de00a0
Create Date: 2026-05-07 10:42:12.281305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '3cf82448f25f'
down_revision = '4da5b9de00a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_services')
    op.drop_table('credential')
    op.drop_table('checklist_reviews')
    op.drop_table('credential_group')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('checklist_reviews',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('comentario', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['checklist_services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credential',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('username', sa.VARCHAR(length=200), nullable=True),
    sa.Column('url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('password_encrypted', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['credential_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_services',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre_cliente', sa.VARCHAR(length=100), nullable=False),
    sa.Column('tipo_tecnologia', sa.VARCHAR(length=50), nullable=False),
    sa.Column('_config_encrypted', sa.TEXT(), nullable=True),
    sa.Column('estado_actual', sa.VARCHAR(length=20), nullable=True),
    sa.Column('mensaje_error', sa.VARCHAR(length=255), nullable=True),
    sa.Column('ultima_data', sqlite.JSON(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
