"""Add credentials module tables

Revision ID: 4da5b9de00a0
Revises: 55ce9998f249
Create Date: 2026-01-20 23:39:33.437837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4da5b9de00a0'
down_revision = '55ce9998f249'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['credential_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ioc', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ioc_tipo'), ['tipo'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    with op.batch_alter_table('vt_ioc', schema=None) as batch_op:
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_vt_ioc_tipo'), ['tipo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vt_ioc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vt_ioc_tipo'))
        batch_op.alter_column('ticket_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    with op.batch_alter_table('ioc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ioc_tipo'))

    op.drop_table('credential')
    op.drop_table('credential_group')
    # ### end Alembic commands ###
