"""Agregar modulo checklist con encriptacion

Revision ID: 55ce9998f249
Revises: 632d7ad28dd9
Create Date: 2026-01-02 18:07:03.006451

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55ce9998f249'
down_revision = '632d7ad28dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checklist_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_cliente', sa.String(length=100), nullable=False),
    sa.Column('tipo_tecnologia', sa.String(length=50), nullable=False),
    sa.Column('_config_encrypted', mysql.TEXT(), nullable=True),
    sa.Column('estado_actual', sa.String(length=20), nullable=True),
    sa.Column('mensaje_error', sa.String(length=255), nullable=True),
    sa.Column('ultima_data', mysql.JSON(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('checklist_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('comentario', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['checklist_services.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('checklist_reviews')
    op.drop_table('checklist_services')
    # ### end Alembic commands ###
