"""Actualizacion inicial modelos VT y limpieza

Revision ID: 632d7ad28dd9
Revises: 
Create Date: 2025-12-06 01:02:30.363529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '632d7ad28dd9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_check')
    with op.batch_alter_table('ioc', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_ioc_valor'), ['valor'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('virustotal_api_key',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('vt_ioc', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_vt_ioc_valor'), ['valor'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vt_ioc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vt_ioc_valor'))
        batch_op.alter_column('valor',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('virustotal_api_key',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('ioc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ioc_valor'))
        batch_op.alter_column('valor',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('manual_check',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fecha', sa.DATETIME(), nullable=True),
    sa.Column('usuario_id', sa.INTEGER(), nullable=True),
    sa.Column('valor', sa.TEXT(), nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=50), nullable=True),
    sa.Column('vt_score', sa.VARCHAR(length=20), nullable=True),
    sa.Column('vt_permalink', sa.VARCHAR(length=255), nullable=True),
    sa.Column('vt_motores_json', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
