"""add umbrella client herramienta job resultado tables

Revision ID: 6b9cfbbdf5f7
Revises: 73088870add2
Create Date: 2026-06-02 01:09:32.390200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9cfbbdf5f7'
down_revision = '73088870add2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('umbrella_cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('client_id_enc', sa.String(length=512), nullable=True),
    sa.Column('client_secret_enc', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umbrella_herramienta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['umbrella_cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('umbrella_herramienta', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_umbrella_herramienta_cliente_id'), ['cliente_id'], unique=False)

    op.create_table('umbrella_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herramienta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('input_filename', sa.String(length=255), nullable=True),
    sa.Column('column_name', sa.String(length=100), nullable=True),
    sa.Column('label_name', sa.String(length=50), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('labeled', sa.Integer(), nullable=True),
    sa.Column('skipped', sa.Integer(), nullable=True),
    sa.Column('failed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['herramienta_id'], ['umbrella_herramienta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('umbrella_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_umbrella_job_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_umbrella_job_herramienta_id'), ['herramienta_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_umbrella_job_status'), ['status'], unique=False)

    op.create_table('umbrella_app_resultado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('http_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['umbrella_job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('umbrella_app_resultado', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_umbrella_app_resultado_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_umbrella_app_resultado_status'), ['status'], unique=False)

    with op.batch_alter_table('ioc', schema=None) as batch_op:
        batch_op.alter_column('valor',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_ioc_valor'), ['valor'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ioc', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ioc_valor'))
        batch_op.alter_column('valor',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('umbrella_app_resultado', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_umbrella_app_resultado_status'))
        batch_op.drop_index(batch_op.f('ix_umbrella_app_resultado_job_id'))

    op.drop_table('umbrella_app_resultado')
    with op.batch_alter_table('umbrella_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_umbrella_job_status'))
        batch_op.drop_index(batch_op.f('ix_umbrella_job_herramienta_id'))
        batch_op.drop_index(batch_op.f('ix_umbrella_job_created_at'))

    op.drop_table('umbrella_job')
    with op.batch_alter_table('umbrella_herramienta', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_umbrella_herramienta_cliente_id'))

    op.drop_table('umbrella_herramienta')
    op.drop_table('umbrella_cliente')
    # ### end Alembic commands ###
