"""vault_keepass_schema

Revision ID: c2c533f5e0cb
Revises: 3c60eec8f741
Create Date: 2026-06-16 12:41:26.950889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2c533f5e0cb'
down_revision = '3c60eec8f741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vault_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('icon_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['vault_group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('vault_entry_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('field_key', sa.String(length=100), nullable=False),
    sa.Column('field_value_enc', sa.Text(), nullable=False),
    sa.Column('is_protected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['vault_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vault_audit_log', schema=None, recreate='always') as batch_op:
        batch_op.create_foreign_key('fk_vault_audit_log_entry_id', 'vault_entry', ['entry_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('vault_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('icon_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint('uq_vault_entry_uuid', ['uuid'])
        batch_op.create_foreign_key('fk_vault_entry_group_id', 'vault_group', ['group_id'], ['id'])

    # Poblar uuid en entradas existentes (SQLite doesn't apply server defaults to existing rows)
    import uuid as _uuid
    conn = op.get_bind()
    existing = conn.execute(sa.text("SELECT id FROM vault_entry WHERE uuid IS NULL")).fetchall()
    for row in existing:
        conn.execute(
            sa.text("UPDATE vault_entry SET uuid = :u WHERE id = :i"),
            {"u": str(_uuid.uuid4()), "i": row[0]}
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vault_entry', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vault_entry_group_id', type_='foreignkey')
        batch_op.drop_constraint('uq_vault_entry_uuid', type_='unique')
        batch_op.drop_column('icon_id')
        batch_op.drop_column('expires_at')
        batch_op.drop_column('group_id')
        batch_op.drop_column('uuid')

    with op.batch_alter_table('vault_audit_log', schema=None, recreate='always') as batch_op:
        batch_op.create_foreign_key('fk_vault_audit_log_entry_id', 'vault_entry', ['entry_id'], ['id'])

    op.drop_table('vault_entry_field')
    op.drop_table('vault_group')
    # ### end Alembic commands ###
